### PR TITLE
README.md fork, Check and Add Issues new

### PR DESCRIPTION
**Pull request by oleksis**

### CODE REVIEW

**Comment by oleksis** [comment]
@khuyentran1401 I think working in this ideas for make Workflows from your Repo to Forks. If you have others let me know!

Fork in push initial 
* Copy issues from origin repo to local issues folder

Actions on Issues:
* Create issue
        - Copy issue to folder issues
* Delete issue
        - Delete issue from folder issues

Actions on Releases:
* Sync issues folder with owner repo Issues (API)
         - Use Create Issue From File action

Actions on Push Requests (PR):
* Sync issues folder with Issus owner repo

        
Future options :
* Use Project Dashboard for when the users make PR reorganize the Issues in columns like To do, In progress, Done (ex: https://github.com/oleksis/machine-learning-articles/projects/1)

* Make index.html for gh-pages with the awesome-machine-learning-articles

**Comment by khuyentran1401** [comment]
@oleksis Thank you for contemplating these great ideas. I especially like the future options. It seems like you make it easy for the user to create, delete the issues, as well as sync issues with the author's folder. There is one thing that I was wondering about. Wouldn't it be easier for users just to create a new issue from my repo? What the benefits they gain from taking extra steps to fork, create issues, then merge the issues? It would be great if you could give me your thoughts on that.

It is innovative for you to think about using the project dashboard to organize the issues. What are some examples that you think users would consider organizing their articles like this?

The index.html is a good idea. We can also consider that
-

**Comment by oleksis** [comment]
Hello @khuyentran1401  My proposal is to manage issues. Until today a user can collaborate by creating an issue directly in your repo. This results in the collaboration being very good or not. What happens if someone makes an issue that is not related to a topic on the list? This would create a huge responsibility for someone (like you) to review the issue and make sure it is correct. As a result the end user (a machine learning reader) can access the list and find topics unrelated to the repo.

The idea about the Project Dashboard is to use it as a filter to generate a final list. For example:

To do -> In progress -> Done

Column To do:
* Copy of the original issues proposed for review
Column In progress:
* Issues for review
Column Done:
* Issues ready to be published as "official" repo list (candidate to generate an index.html for gh-pages for example)

The idea of ​​making a fork is because they ask to exist users who are interested in the repository but to add other articles to their list. To do this they create a fork and manage their list of items

I hope to reach an agreement. These are some ideas that I think would make the repository more interesting and fun

Cheers!

**Comment by khuyentran1401** [comment]
Hi @oleksis, I agree that forking is a good idea to customize the repo for their own article list. So that will be a good idea. And I guess when they create pull requests, I can merge their list with my article list? That is good so far. I just wonder if the issues in the issues folder can appear on the tab Issues in my repo after merging? 

It would be nice if the users can create their list in their repo with the tag that they like. The whole process of copying to the issues and pushing requests to the owner should be quick and easy (I think this is also what you want). Is this possible? I feel like I should create better README for the instruction about what to do after forking. Maybe you can help me with better instruction?

I understand the purpose of Project Dashboard and this would be useful to filter appropriate articles and be published as an "official" repo list. I look forward to seeing some ideas that you have of how the index.html gh.pages would be like.

Thank you for the clarity. I like your ideas and I think we should try out with those since I believe those will make this repo more useful and user friendly. What are your thoughts on how we can go forward with these ideas?

**Pull request merged**
